name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  nest-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_REF }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_REF }}

      - name: Create GitHub Issue on Failure
        if: failure() && steps.typescript-check.outcome == 'failure'
        run: |
          gh issue create \
            --title "Build failed during TypeScript Check" \
            --body "The build failed due to TypeScript check errors. Please check the logs for more details." \
            --assignee ${{ github.actor }} \
            --labels "bug"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
